CREATE TABLE `pre_approvals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int NOT NULL,
	`vehicleId` int,
	`referenceNumber` varchar(32) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`idNumberMasked` varchar(32),
	`email` varchar(320) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`employmentStatus` enum('permanent','contract','self_employed','pensioner','unemployed'),
	`employer` varchar(255),
	`monthsEmployed` int,
	`grossMonthlyIncome` decimal(12,2),
	`netMonthlyIncome` decimal(12,2),
	`totalMonthlyExpenses` decimal(12,2),
	`existingDebtMonthly` decimal(12,2),
	`vehiclePrice` decimal(12,2),
	`desiredDeposit` decimal(12,2),
	`desiredTermMonths` int,
	`hasTradeIn` tinyint NOT NULL DEFAULT 0,
	`tradeInDescription` varchar(500),
	`notes` text,
	`status` enum('submitted','in_review','more_info_needed','approved','declined','withdrawn') NOT NULL DEFAULT 'submitted',
	`agentReply` text,
	`language` varchar(8) DEFAULT 'en',
	`humanDecision` enum('none','approved','declined','more_info') NOT NULL DEFAULT 'none',
	`humanNote` text,
	`decidedBy` int,
	`decidedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pre_approvals_id` PRIMARY KEY(`id`),
	CONSTRAINT `pre_approvals_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
--> statement-breakpoint
ALTER TABLE `agent_activity` MODIFY COLUMN `agentId` enum('email','calling','booking','prospector','improvement','whatsapp','accountant','fallback','preapproval') NOT NULL;