CREATE TABLE `test_drive_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int NOT NULL,
	`vehicleId` int,
	`referenceNumber` varchar(32) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerContact` varchar(320) NOT NULL,
	`inboundMessage` text,
	`outboundReply` text NOT NULL,
	`requestedSlotStart` timestamp,
	`requestedSlotEnd` timestamp,
	`suggestedSlotStart` timestamp,
	`suggestedSlotEnd` timestamp,
	`confirmedSlotStart` timestamp,
	`confirmedSlotEnd` timestamp,
	`channel` enum('website','whatsapp','call','web_chat') NOT NULL,
	`language` varchar(8) DEFAULT 'en',
	`status` enum('requested','confirmed','rescheduled','completed','cancelled','no_show') NOT NULL DEFAULT 'requested',
	`notes` text,
	`resolvedAt` timestamp,
	`resolvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `test_drive_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `test_drive_bookings_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
