CREATE TABLE `trade_in_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int,
	`contactName` varchar(255),
	`contactEmail` varchar(255),
	`contactPhone` varchar(32),
	`make` varchar(80) NOT NULL,
	`model` varchar(120) NOT NULL,
	`year` int NOT NULL,
	`mileageKm` int NOT NULL,
	`transmission` enum('manual','automatic','cvt','dct') NOT NULL,
	`fuel` enum('petrol','diesel','hybrid','electric') NOT NULL,
	`bodyType` varchar(60) NOT NULL,
	`condition` enum('excellent','good','fair','poor') NOT NULL,
	`serviceHistory` enum('full_dealer','full_independent','partial','none') NOT NULL,
	`notes` text,
	`estimateLow` int NOT NULL,
	`estimateMid` int NOT NULL,
	`estimateHigh` int NOT NULL,
	`confidence` enum('low','medium','high') NOT NULL,
	`factorBreakdown` text NOT NULL,
	`memoMarkdown` text NOT NULL,
	`language` varchar(5) NOT NULL DEFAULT 'en',
	`status` enum('estimated','principal_review','offer_sent','accepted','rejected','expired') NOT NULL DEFAULT 'estimated',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trade_in_quotes_id` PRIMARY KEY(`id`)
);
