CREATE TABLE `bee_scorecard` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int NOT NULL,
	`beeLevel` int NOT NULL,
	`beeScore` decimal(5,2),
	`ownershipScore` decimal(5,2) DEFAULT '0',
	`managementScore` decimal(5,2) DEFAULT '0',
	`employmentEquityScore` decimal(5,2) DEFAULT '0',
	`skillsDevelopmentScore` decimal(5,2) DEFAULT '0',
	`enterpriseDevelopmentScore` decimal(5,2) DEFAULT '0',
	`socioEconomicScore` decimal(5,2) DEFAULT '0',
	`preferentialProcurementScore` decimal(5,2) DEFAULT '0',
	`blackOwnershipPercentage` decimal(5,2),
	`blackManagementPercentage` decimal(5,2),
	`blackEmployeePercentage` decimal(5,2),
	`trainingSpendPercentage` decimal(5,2),
	`preferentialProcurementSpend` decimal(12,2),
	`status` enum('compliant','non_compliant','pending_verification') NOT NULL DEFAULT 'pending_verification',
	`lastVerified` timestamp,
	`nextVerificationDue` timestamp,
	`gapAnalysis` json,
	`improvementActions` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bee_scorecard_id` PRIMARY KEY(`id`),
	CONSTRAINT `bee_scorecard_dealershipId_unique` UNIQUE(`dealershipId`)
);
--> statement-breakpoint
CREATE TABLE `complaints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int NOT NULL,
	`complaintNumber` varchar(50) NOT NULL,
	`complaintType` enum('service_quality','pricing','warranty','financing','vehicle_condition','delivery','communication','staff_conduct','safety','other') NOT NULL,
	`complainantName` varchar(255) NOT NULL,
	`complainantEmail` varchar(320) NOT NULL,
	`complainantPhone` varchar(32) NOT NULL,
	`complainantIdNumber` varchar(64),
	`vehicleId` int,
	`invoiceId` int,
	`description` text NOT NULL,
	`attachmentUrl` varchar(500),
	`severity` enum('low','medium','high','critical') NOT NULL,
	`priority` enum('low','medium','high','urgent') NOT NULL,
	`status` enum('received','acknowledged','under_investigation','proposed_resolution','resolved','escalated','closed') NOT NULL DEFAULT 'received',
	`receivedDate` timestamp NOT NULL DEFAULT (now()),
	`acknowledgedDate` timestamp,
	`resolutionDeadline` timestamp,
	`resolvedDate` timestamp,
	`assignedTo` int,
	`investigationNotes` text,
	`rootCause` text,
	`proposedResolution` text,
	`actualResolution` text,
	`compensationOffered` decimal(12,2),
	`compensationAccepted` int,
	`compensationPaid` int,
	`compensationDate` timestamp,
	`escalatedTo` int,
	`escalationReason` text,
	`escalationDate` timestamp,
	`reportedToNrcs` int DEFAULT 0,
	`reportedToConsumerProtection` int DEFAULT 0,
	`regulatoryReferenceNumber` varchar(100),
	`complainantSatisfaction` int,
	`complainantFeedback` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `complaints_id` PRIMARY KEY(`id`),
	CONSTRAINT `complaints_complaintNumber_unique` UNIQUE(`complaintNumber`)
);
--> statement-breakpoint
CREATE TABLE `nrcs_affordability_assessment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`dealershipId` int NOT NULL,
	`monthlyIncome` decimal(12,2) NOT NULL,
	`monthlyExpenses` decimal(12,2) NOT NULL,
	`existingDebtObligations` decimal(12,2) NOT NULL,
	`creditScore` int,
	`creditHistory` varchar(32),
	`proposedLoanAmount` decimal(12,2) NOT NULL,
	`proposedInterestRate` decimal(5,2) NOT NULL,
	`proposedLoanTerm` int NOT NULL,
	`proposedMonthlyPayment` decimal(12,2) NOT NULL,
	`disposableIncome` decimal(12,2),
	`debtToIncomeRatio` decimal(5,2),
	`loanPaymentToIncomeRatio` decimal(5,2),
	`affordabilityScore` decimal(5,2),
	`isAffordable` int NOT NULL,
	`assessmentReason` text,
	`riskLevel` enum('low','medium','high','very_high') NOT NULL,
	`recommendedLoanAmount` decimal(12,2),
	`recommendedMonthlyPayment` decimal(12,2),
	`debtCounsellingRequired` int DEFAULT 0,
	`debtCounsellingReferral` varchar(255),
	`assessedBy` int NOT NULL,
	`assessmentDate` timestamp NOT NULL DEFAULT (now()),
	`reviewedBy` int,
	`reviewDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nrcs_affordability_assessment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `popia_data_subject_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealershipId` int NOT NULL,
	`requestType` enum('access','correction','deletion','objection','restrict','portability') NOT NULL,
	`requesterName` varchar(255) NOT NULL,
	`requesterEmail` varchar(320) NOT NULL,
	`requesterPhone` varchar(32),
	`requesterIdNumber` varchar(64),
	`dataSubjectDescription` text,
	`reason` text,
	`status` enum('received','acknowledged','under_review','approved','denied','completed','withdrawn') NOT NULL DEFAULT 'received',
	`receivedDate` timestamp NOT NULL DEFAULT (now()),
	`acknowledgedDate` timestamp,
	`completionDeadline` timestamp,
	`completedDate` timestamp,
	`responseNotes` text,
	`responseDocument` varchar(500),
	`denialReason` text,
	`processedBy` int,
	`verifiedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `popia_data_subject_requests_id` PRIMARY KEY(`id`)
);
