import type { Resource } from "./types";

export const RESOURCES: Resource[] = [
  {
    id: "founding-sales",
    resource: "Founding Sales — Pete Kazanjy (read Ch. 4–5 first: prospecting + appointment setting)",
    format: "book",
    link: "https://www.foundingsales.com/",
    why: "You are a technical founder who still does not have a verbal commercial conversation with the person who can pay. Kazanjy wrote this for that exact gap: narrative, named accounts, and demo-setting — not enterprise theatre. Apply tomorrow: ten named principals, one four-sentence ask for 15 minutes, no product tour in the email.",
    struggles: ["first_customers", "founder_outbound", "reach_the_owner"],
    applyThisWeek: "Run his early prospecting + appointment-setting chapters as a checklist on 10 named owners.",
    minutes: 90,
  },
  {
    id: "demand-side-sales",
    resource: "Demand-Side Sales 101 — Bob Moesta",
    format: "book",
    link: "https://www.amazon.com/Demand-Side-Sales-101-Customers-Progress/dp/1544509987",
    why: "Owner-operators stall when you recite agents and features. Moesta trains you to find the struggling moment they are already in (leads dying on WhatsApp, weekend stock, a contract they resent) and help them buy progress. Use this on the next live call instead of a dashboard walkthrough.",
    struggles: ["demand_side_sales", "first_customers", "sa_b2b"],
    applyThisWeek: "Write 8 struggling-moment questions. Use only those on the next dealer call.",
    minutes: 120,
  },
  {
    id: "sales-pitch",
    resource: "Sales Pitch — April Dunford (plus the free Sales Pitch Storyboard)",
    format: "book",
    link: "https://www.aprildunford.com/books",
    why: "Your default demo is a feature walkthrough of a large surface. Dunford's eight-step pitch makes differentiated value the star and treats 'do nothing' / 'stay in the current contract' as the real competitor. Fill the storyboard once, then use it as the only 15-minute talk track.",
    struggles: ["demand_side_sales", "pricing", "first_customers"],
    applyThisWeek: "Fill the storyboard. Open the next call with market insight + alternative, not a login.",
    minutes: 80,
  },
  {
    id: "mom-test",
    resource: "The Mom Test — Rob Fitzpatrick",
    format: "book",
    link: "https://www.momtestbook.com/",
    why: "You have been talking to the market through research pipelines and your own product. Fitzpatrick is the anti-compliment rulebook: past behaviour, specifics, no pitching in discovery. Use it this week on three principals you already found — if they cannot name a lead that died last month, you do not have a sale, you have politeness.",
    struggles: ["demand_side_sales", "build_trap", "first_customers"],
    applyThisWeek: "Three 20-minute calls. Ask only about last month's lost deals. Do not mention your product until they ask.",
    minutes: 70,
  },
  {
    id: "build-trap",
    resource: "Escaping the Build Trap — Melissa Perri (Ch. 1–3: outputs vs outcomes)",
    format: "book",
    link: "https://www.oreilly.com/library/view/escaping-the-build/9781491973783/",
    why: "A cleaner prospect list and another agent is output. A signed pilot is an outcome. Perri is the shortest language for the pattern you are in: shipping as a proxy for progress. Read the value-exchange chapters, then freeze non-sales code until ten conversations are done.",
    struggles: ["build_trap", "time_split", "ship_ai"],
    applyThisWeek: "Define one outcome metric for 14 days: conversations with named principals. Code is allowed only if it unblocks a conversation.",
    minutes: 60,
  },
  {
    id: "shape-up",
    resource: "Shape Up — Ryan Singer (free). Read 'Shaping' + 'Appetite', skip the 50-person process.",
    format: "book",
    link: "https://basecamp.com/shapeup",
    why: "You do not need Basecamp's org design. You need appetite: a six-week-or-less bet, shaped before you build, with a hill to the finish. Use it to stop unbounded agent work. Shape one sales-enabling slice (a talk track + a one-page offer), not another subsystem.",
    struggles: ["build_trap", "time_split", "ship_ai"],
    applyThisWeek: "Set a two-week appetite: offer page + talk track. Anything that does not fit is out of the bet.",
    minutes: 50,
  },
  {
    id: "new-sales-simplified",
    resource: "New Sales. Simplified. — Mike Weinberg (the Sales Story + proactive call chapters)",
    format: "book",
    link: "https://mikeweinberg.com/new-sales-simplified/",
    why: "Weinberg is blunt about calendar math: new business dies when it is not blocked. You need a customer-focused sales story and a same-day telephone follow-up after the email, not another enrichment pass. This is the 'make the call' book.",
    struggles: ["founder_outbound", "time_split", "reach_the_owner"],
    applyThisWeek: "Block 90 minutes. Call the ten names. Use his story: who you help, what is broken, the specific ask.",
    minutes: 75,
  },
  {
    id: "monetizing-innovation",
    resource: "Monetizing Innovation — Ramanujam & Tacke (willingness-to-pay before more features)",
    format: "book",
    link: "https://www.amazon.com/Monetizing-Innovation-Companies-Design-Product/dp/1119240867",
    why: "You have a wide product and several price documents. This book is the rule 'have the willingness-to-pay talk early' — design the pilot around what an owner will actually pay this month, not around the full agent roster. Stops feature-shock: selling a platform when they will only buy a wedge.",
    struggles: ["pricing", "build_trap", "first_customers"],
    applyThisWeek: "Ask three owners: 'If this worked, what would you pay for the first 30 days, and what would you cut?' Price the wedge, not the platform.",
    minutes: 90,
  },
  {
    id: "simple-numbers",
    resource: "Simple Numbers, Straight Talk, Big Profits! — Greg Crabtree",
    format: "book",
    link: "https://gregcrabtree.net/books/simple-numbers-straight-talk-big-profits/",
    why: "You need cash physics, not startup-finance theatre. Crabtree's four forces (tax, debt, core capital, then distributions) and the 5/10/15% profit language fit a one-person company that must get paid in South Africa. Apply: a one-page weekly cash view and a market wage for yourself even at zero revenue, so the pilot price has to cover reality.",
    struggles: ["cash", "pricing", "sa_b2b"],
    applyThisWeek: "Write this week's cash, tax set-aside, and the minimum pilot that covers 2 months of operating costs.",
    minutes: 60,
  },
  {
    id: "30mpc",
    resource: "30 Minutes to President's Club — Armand Farrokh & Nick Cegelski (SELL episodes on 4-sentence email + multi-thread to the decision maker)",
    format: "podcast",
    link: "https://www.30mpc.com/",
    why: "Tactical, not mindset. You need the 4-sentence cold email and the move from the mailbox that bounces to the human who can sign. Skip leadership episodes. Steal language, then send.",
    struggles: ["founder_outbound", "reach_the_owner"],
    applyThisWeek: "Rewrite one email to four sentences. Send it to ten named owners. Call the same day.",
    minutes: 30,
  },
  {
    id: "sfrtu",
    resource: "Startups for the Rest of Us — Rob Walling (episodes on first customers and founder-led sales, not VC)",
    format: "podcast",
    link: "https://www.startupsfortherestofus.com/",
    why: "Bootstrapped SaaS, not unicorn advice. Walling's show is for founders who need paying customers without a sales team. Filter for first-10-customers / outbound, ignore later-scale hiring.",
    struggles: ["first_customers", "founder_outbound", "time_split"],
    applyThisWeek: "One episode while you walk. Then do the ten-name block before you open a laptop for code.",
    minutes: 35,
  },
  {
    id: "positioning-show",
    resource: "The Positioning Show — April Dunford (pitch structure episodes)",
    format: "podcast",
    link: "https://www.positioning.show/",
    why: "Shorter than the book when you need the talk track in your ear the morning of a call. Especially the episodes on 'do nothing' as competitor and why features in the first five minutes lose.",
    struggles: ["demand_side_sales", "pricing"],
    applyThisWeek: "Listen to one pitch-structure episode. Deliver that structure, not your agent list, on the next call.",
    minutes: 30,
  },
  {
    id: "complex-systems",
    resource: "Complex Systems — Patrick McKenzie (patio11). Finance/infrastructure episodes only when they change how you get paid.",
    format: "podcast",
    link: "https://www.complexsystemspodcast.com/",
    why: "You touch payments, email reputation, and trust. patio11 explains the boring systems that decide whether money and mail actually move. Skip curiosity episodes. Use the ones on payments, fraud, and operational trust before you pick a SA payment path.",
    struggles: ["cash", "sa_b2b", "reach_the_owner"],
    applyThisWeek: "If a payments episode is in the brief, decide EFT vs card for the first invoice the same morning.",
    minutes: 40,
  },
  {
    id: "patio11",
    resource: "Patrick McKenzie (patio11) — Kalzumeus essays + Bits about Money",
    format: "creator",
    link: "https://www.kalzumeus.com/",
    why: "Not a guru feed. patio11 is the practitioner voice on charging, email, and not apologising for price. Pair with Bits about Money (https://www.bitsaboutmoney.com/) when a payments or deliverability decision is on the desk this week.",
    struggles: ["pricing", "cash", "reach_the_owner"],
    applyThisWeek: "Read one essay on charging. Raise the pilot to a number that covers two months of costs. Say it out loud once.",
    minutes: 25,
  },
  {
    id: "asmartbear",
    resource: "Jason Cohen — A Smart Bear (pricing, positioning, 'too expensive')",
    format: "creator",
    link: "https://longform.asmartbear.com/",
    why: "Bootstrapped-then-scaled operator. His pricing and 'too expensive is not the reason' pieces map to an owner saying no because they cannot see weekend progress, not because Rands are high. Read one longform, then rewrite the offer sentence.",
    struggles: ["pricing", "first_customers", "build_trap"],
    applyThisWeek: "Rewrite the offer as outcome-per-month, not a feature matrix.",
    minutes: 25,
  },
  {
    id: "aprildunford-x",
    resource: "April Dunford on X — @aprildunford",
    format: "creator",
    link: "https://x.com/aprildunford",
    why: "Short positioning corrections you can apply before a call. Mute everything that is not a pitch or alternative-product insight. She is in the brief because your talk track is the bottleneck, not because she is famous.",
    struggles: ["demand_side_sales", "pricing"],
    applyThisWeek: "Steal one sentence about alternatives. Put it as line two of the email.",
    minutes: 10,
  },
  {
    id: "clay-deliverability",
    resource: "B2B Cold Email Deliverability — Clay (21 practices)",
    format: "essay",
    link: "https://www.clay.com/blog/b2b-cold-email-deliverability",
    why: "You already learned that generic mailboxes bounce and invented addresses poison the domain. This is the practical SPF/DKIM/DMARC, warmup, and named-inbox list — not a growth-hack thread. Apply before you send the next ten: authentication, named addresses only, volume cap.",
    struggles: ["reach_the_owner", "founder_outbound"],
    applyThisWeek: "Check SPF/DKIM/DMARC. Send only to named @dealer-domain. Cap volume. No catch-alls.",
    minutes: 40,
  },
  {
    id: "pg-dts",
    resource: "Do Things That Don't Scale — Paul Graham",
    format: "essay",
    link: "https://paulgraham.com/ds.html",
    why: "The unfashionable instruction you need this month: onboard the first dealers by hand. Not more automation. Sit next to the principal, import the stock yourself, watch where they stall, close. You already over-automated the hunt.",
    struggles: ["first_customers", "build_trap", "ship_ai"],
    applyThisWeek: "Offer to sit in the yard / screenshare the first import yourself. That is the sale.",
    minutes: 20,
  },
  {
    id: "pg-makers",
    resource: "Maker's Schedule, Manager's Schedule — Paul Graham",
    format: "essay",
    link: "https://paulgraham.com/makersschedule.html",
    why: "You default to maker days, then wonder why no one was called. This is the shortest explanation of why selling cannot live in leftover minutes. Apply: one manager morning (calls) and one maker afternoon (only if the calls happened).",
    struggles: ["time_split", "founder_outbound"],
    applyThisWeek: "Calendar: 09:00–11:00 SAST is calling. Code is locked until the ten are attempted.",
    minutes: 15,
  },
  {
    id: "saas-playbook-sales",
    resource: "The SaaS Playbook — Rob Walling (the sales / first customers chapters only)",
    format: "book",
    link: "https://robwalling.com/",
    why: "Bootstrapped metrics and founder-led sales without a team. Skip the later hiring and exit chapters. Use the first-customers material to set a weekly conversation quota, not a vanity MRR model.",
    struggles: ["first_customers", "time_split", "pricing"],
    applyThisWeek: "Set a weekly quota: 10 conversations, 2 next-steps, 1 written offer. Track only those.",
    minutes: 70,
  },
  {
    id: "payfast-docs",
    resource: "PayFast merchant docs — get a first invoice actually payable this week",
    format: "course",
    link: "https://developers.payfast.co.za/docs",
    why: "Learning 'finance' in the abstract will not collect. SA owners pay EFT and local cards. This is the just-in-time path to a payable link or EFT instruction on the offer page. Pair with Crabtree so the number on the invoice is real.",
    struggles: ["cash", "sa_b2b", "pricing"],
    applyThisWeek: "Stand up one payable path (EFT details + PayFast) and put it on the one-page offer.",
    minutes: 45,
  },
  {
    id: "naamsa-context",
    resource: "NAAMSA / Business Day motoring — this week's vehicle-sales numbers",
    format: "newsletter",
    link: "https://www.businessday.co.za/motoring/",
    why: "Not industry trivia. Principals live in last month's units. Opening a call with a current SA sales print (and what it does to used-stock pressure) is demand-side: you are in their morning, not in your product. The brief will pull this when it is fresh.",
    struggles: ["sa_b2b", "demand_side_sales"],
    applyThisWeek: "Use one current number as sentence one of the next email or call.",
    minutes: 10,
  },
];

export const RESOURCE_BY_ID = Object.fromEntries(RESOURCES.map((r) => [r.id, r]));
