import type { Source } from "./types";

export const SOURCES: Source[] = [
  {
    id: "30mpc-feed",
    name: "30 Minutes to President's Club",
    kind: "podcast",
    url: "https://www.30mpc.com/",
    rss: "https://feeds.transistor.fm/30mpc",
    why: "4-sentence email, decision-maker threading, call openers. Brief only when the episode is outbound or discovery.",
    struggles: ["founder_outbound", "reach_the_owner"],
  },
  {
    id: "sfrtu-feed",
    name: "Startups for the Rest of Us",
    kind: "podcast",
    url: "https://www.startupsfortherestofus.com/",
    rss: "https://www.startupsfortherestofus.com/feed",
    why: "Bootstrapped first customers. Skip later-scale and conference recap episodes.",
    struggles: ["first_customers", "founder_outbound"],
  },
  {
    id: "positioning-feed",
    name: "The Positioning Show",
    kind: "podcast",
    url: "https://www.positioning.show/",
    rss: "https://feeds.simplecast.com/l2iWMr4c",
    why: "Pitch structure. Include when it changes what you say in the first five minutes.",
    struggles: ["demand_side_sales", "pricing"],
  },
  {
    id: "complex-systems-feed",
    name: "Complex Systems (patio11)",
    kind: "podcast",
    url: "https://www.complexsystemspodcast.com/",
    rss: "https://www.complexsystemspodcast.com/rss/",
    why: "Payments, mail, trust systems. Drop if it is curiosity infrastructure.",
    struggles: ["cash", "reach_the_owner"],
  },
  {
    id: "latent-space",
    name: "Latent Space",
    kind: "podcast",
    url: "https://www.latent.space/",
    rss: "https://api.substack.com/feed/podcast/1084089.rss",
    why: "Only if it is about shipping an AI product someone pays for — not model gossip.",
    struggles: ["ship_ai"],
  },
  {
    id: "x-aprildunford",
    name: "April Dunford",
    kind: "x",
    url: "https://x.com/aprildunford",
    why: "Positioning corrections. No lifestyle, no quote-cards.",
    struggles: ["demand_side_sales", "pricing"],
  },
  {
    id: "x-patio11",
    name: "Patrick McKenzie",
    kind: "x",
    url: "https://x.com/patio11",
    why: "Charging, email, payments. Ignore jokes and quote-tweets.",
    struggles: ["pricing", "cash", "reach_the_owner"],
  },
  {
    id: "x-asmartbear",
    name: "Jason Cohen",
    kind: "x",
    url: "https://x.com/asmartbear",
    why: "Pricing and bootstrapped operating. Skip conference travel.",
    struggles: ["pricing", "first_customers"],
  },
  {
    id: "x-paulg",
    name: "Paul Graham",
    kind: "x",
    url: "https://x.com/paulg",
    why: "Only essays/links on doing unscalable sales work. Ignore general startup commentary.",
    struggles: ["build_trap", "first_customers"],
  },
  {
    id: "x-30mpc",
    name: "30MPC",
    kind: "x",
    url: "https://x.com/30mpc",
    why: "Stealable talk tracks. Drop anything that is a course funnel without a tactic.",
    struggles: ["founder_outbound"],
  },
  {
    id: "x-moneyweb",
    name: "Moneyweb",
    kind: "x",
    url: "https://x.com/Moneyweb",
    why: "SA rates, payments, business mood that a principal feels this week.",
    struggles: ["sa_b2b", "cash"],
  },
  {
    id: "ig-moneyweb",
    name: "Moneyweb",
    kind: "instagram",
    url: "https://www.instagram.com/moneyweb/",
    why: "Low-signal vs RSS. Kept because you asked for IG; the brief will almost never promote an IG post over a primary article.",
    struggles: ["sa_b2b"],
  },
  {
    id: "ig-businesstech",
    name: "BusinessTech",
    kind: "instagram",
    url: "https://www.instagram.com/businesstechsa/",
    why: "SA business headlines only. Prefer the BusinessTech RSS when both exist.",
    struggles: ["sa_b2b"],
  },
  {
    id: "ig-dailymaverick",
    name: "Daily Maverick",
    kind: "instagram",
    url: "https://www.instagram.com/dailymaverick/",
    why: "Backup awareness. The brief uses Daily Maverick RSS, not the grid.",
    struggles: ["sa_b2b"],
  },
  {
    id: "nl-smartbear",
    name: "A Smart Bear",
    kind: "newsletter",
    url: "https://longform.asmartbear.com/",
    rss: "https://longform.asmartbear.com/rss/",
    why: "Longform on pricing and strategy. Include one piece, never a dump.",
    struggles: ["pricing", "build_trap"],
  },
  {
    id: "nl-bam",
    name: "Bits about Money",
    kind: "newsletter",
    url: "https://www.bitsaboutmoney.com/",
    rss: "https://www.bitsaboutmoney.com/rss/",
    why: "Payments and financial plumbing. Include when it changes an invoice or mail decision.",
    struggles: ["cash", "reach_the_owner"],
  },
  {
    id: "nl-batch",
    name: "The Batch (Andrew Ng)",
    kind: "newsletter",
    url: "https://www.deeplearning.ai/the-batch/",
    rss: "https://www.deeplearning.ai/the-batch/feed",
    why: "AI without launch-day clickbait. Keep only items that change how you ship or sell an AI wedge.",
    struggles: ["ship_ai"],
  },
  {
    id: "nl-importai",
    name: "Import AI (Jack Clark)",
    kind: "newsletter",
    url: "https://importai.substack.com/",
    rss: "https://importai.substack.com/feed",
    why: "Policy/capability, not tools-of-the-week. Rarely in the brief unless it affects a buyer conversation.",
    struggles: ["ship_ai"],
  },
  {
    id: "news-moneyweb",
    name: "Moneyweb",
    kind: "news",
    url: "https://www.moneyweb.co.za/",
    rss: "https://www.moneyweb.co.za/feed/",
    why: "SA business and markets. Filter to rates, payments, SME, auto-adjacent. No market-mover clickbait.",
    struggles: ["sa_b2b", "cash"],
  },
  {
    id: "news-businesstech",
    name: "BusinessTech",
    kind: "news",
    url: "https://businesstech.co.za/",
    rss: "https://businesstech.co.za/news/feed/",
    why: "SA operating reality: banks, fuel, labour, vehicles. Use when a principal would feel it this week.",
    struggles: ["sa_b2b"],
  },
  {
    id: "news-itweb",
    name: "ITWeb",
    kind: "news",
    url: "https://www.itweb.co.za/",
    rss: "https://www.itweb.co.za/rss",
    why: "How SA companies actually buy software. Skip vendor awards.",
    struggles: ["sa_b2b", "first_customers"],
  },
  {
    id: "news-dailymaverick",
    name: "Daily Maverick",
    kind: "news",
    url: "https://www.dailymaverick.co.za/",
    rss: "https://www.dailymaverick.co.za/dmrss/",
    why: "Business desk only. Politics-only pieces are noise for this brief.",
    struggles: ["sa_b2b"],
  },
  {
    id: "news-cars",
    name: "Cars.co.za news",
    kind: "news",
    url: "https://www.cars.co.za/motoring-news/",
    rss: "https://www.cars.co.za/feed/",
    why: "Used-car and dealer-facing numbers. Opening-line fuel for calls.",
    struggles: ["sa_b2b", "demand_side_sales"],
  },
];

export const CLICKBAIT =
  /\b(you won't believe|shocking|must-see|going viral|secret trick|gurus?|hustle|10x your|mind-blown|unhinged|this changes everything|need this in your life)\b/i;

export const RELEVANCE: Record<string, RegExp> = {
  first_customers: /\b(first (10|ten) customers|founder[- ]led sales|pilot|closed[- ]won|getting customers)\b/i,
  founder_outbound: /\b(outbound|cold email|cold call|prospecting|sequence|appointment)\b/i,
  reach_the_owner: /\b(deliverability|spf|dkim|dmarc|inbox|bounce|decision[- ]maker|principal|owner[- ]operator)\b/i,
  build_trap: /\b(build trap|shipping features|outcomes not outputs|do things that don't scale|appetite|shape up)\b/i,
  pricing: /\b(pricing|willingness to pay|packaging|discount|too expensive|offer)\b/i,
  cash: /\b(cash flow|runway|invoice|payfast|eft|payments?|vat|working capital)\b/i,
  demand_side_sales: /\b(jobs to be done|struggling moment|positioning|sales pitch|discovery)\b/i,
  time_split: /\b(calendar|time block|maker's schedule|selling time)\b/i,
  ship_ai: /\b(shipping|eval|reliability|production llm|ai product|whatsapp business)\b/i,
  sa_b2b: /\b(south africa|gauteng|rand|sarb|naamsa|used[- ]car|dealership|sme|load[- ]?shedding)\b/i,
};
