/**
 * Self-Training FAQ Generation System
 * Automatically creates and updates FAQs from customer conversations
 * No manual effort required - chatbot learns and improves itself
 */

export interface ConversationMessage {
  role: "user" | "bot";
  content: string;
  timestamp: Date;
  language: string;
  sentiment: number;
}

export interface ExtractedQuestion {
  question: string;
  answer: string;
  language: string;
  frequency: number;
  sentiment: number;
  confidence: number;
  extractedAt: Date;
  sourceConversations: number[];
}

export interface AutoGeneratedFAQ {
  id: string;
  question: string;
  answer: string;
  language: string;
  category: string;
  frequency: number;
  avgSentiment: number;
  confidence: number;
  autoGenerated: true;
  createdAt: Date;
  lastUpdated: Date;
  usageCount: number;
  satisfactionScore: number;
}

/**
 * Extract questions and answers from conversations
 */
export async function extractQuestionsFromConversations(
  conversations: ConversationMessage[][]
): Promise<ExtractedQuestion[]> {
  const extracted: ExtractedQuestion[] = [];

  for (const conversation of conversations) {
    for (let i = 0; i < conversation.length - 1; i++) {
      const msg = conversation[i];
      const nextMsg = conversation[i + 1];

      // If user message followed by bot response
      if (msg.role === "user" && nextMsg.role === "bot") {
        const question = msg.content;
        const answer = nextMsg.content;
        const language = msg.language;

        // Check if this question already exists
        const existing = extracted.find(
          (q) => q.question.toLowerCase() === question.toLowerCase() && q.language === language
        );

        if (existing) {
          existing.frequency++;
          existing.sourceConversations.push(i);
        } else {
          extracted.push({
            question,
            answer,
            language,
            frequency: 1,
            sentiment: msg.sentiment,
            confidence: calculateConfidence(question, answer),
            extractedAt: new Date(),
            sourceConversations: [i],
          });
        }
      }
    }
  }

  // Sort by frequency
  return extracted.sort((a, b) => b.frequency - a.frequency);
}

/**
 * Calculate confidence score for extracted Q&A
 */
function calculateConfidence(question: string, answer: string): number {
  let confidence = 50; // Base confidence

  // Increase confidence if question is clear
  if (question.length > 10 && question.length < 200) confidence += 15;

  // Increase confidence if answer is substantial
  if (answer.length > 50 && answer.length < 500) confidence += 15;

  // Increase confidence if question has question mark
  if (question.includes("?")) confidence += 10;

  // Increase confidence if answer contains specific details
  if (answer.includes("R$") || answer.includes("ZAR") || answer.match(/\d+/)) confidence += 10;

  return Math.min(100, confidence);
}

/**
 * Generate FAQ entries from extracted questions
 */
export async function generateFAQsFromExtracted(
  extracted: ExtractedQuestion[],
  dealershipId: number
): Promise<AutoGeneratedFAQ[]> {
  const faqs: AutoGeneratedFAQ[] = [];

  // Only create FAQs for questions that appear frequently
  const frequentQuestions = extracted.filter((q) => q.frequency >= 3 && q.confidence >= 60);

  for (const question of frequentQuestions) {
    const faq: AutoGeneratedFAQ = {
      id: `faq_${dealershipId}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      question: question.question,
      answer: question.answer,
      language: question.language,
      category: categorizeQuestion(question.question),
      frequency: question.frequency,
      avgSentiment: question.sentiment,
      confidence: question.confidence,
      autoGenerated: true,
      createdAt: new Date(),
      lastUpdated: new Date(),
      usageCount: 0,
      satisfactionScore: 0,
    };

    faqs.push(faq);
  }

  return faqs;
}

/**
 * Categorize questions automatically
 */
function categorizeQuestion(question: string): string {
  const q = question.toLowerCase();

  if (q.includes("price") || q.includes("cost") || q.includes("afford")) return "Pricing";
  if (q.includes("test drive") || q.includes("drive")) return "Test Drive";
  if (q.includes("finance") || q.includes("loan") || q.includes("payment")) return "Financing";
  if (q.includes("trade") || q.includes("trade-in")) return "Trade-in";
  if (q.includes("warranty") || q.includes("guarantee")) return "Warranty";
  if (q.includes("service") || q.includes("maintenance")) return "Service";
  if (q.includes("color") || q.includes("feature") || q.includes("spec")) return "Specifications";
  if (q.includes("available") || q.includes("stock") || q.includes("inventory")) return "Availability";
  if (q.includes("delivery") || q.includes("ship")) return "Delivery";
  if (q.includes("insurance")) return "Insurance";

  return "General";
}

/**
 * Update existing FAQ with new information
 */
export async function updateFAQWithNewData(
  existingFAQ: AutoGeneratedFAQ,
  newQuestions: ExtractedQuestion[]
): Promise<AutoGeneratedFAQ> {
  const similarQuestions = newQuestions.filter(
    (q) =>
      q.language === existingFAQ.language &&
      calculateSimilarity(q.question, existingFAQ.question) > 0.7
  );

  if (similarQuestions.length > 0) {
    // Update frequency
    existingFAQ.frequency += similarQuestions.reduce((sum, q) => sum + q.frequency, 0);

    // Update answer if new one is better
    const bestAnswer = similarQuestions.reduce((best, q) => {
      return q.confidence > best.confidence ? q : best;
    });

    if (bestAnswer.confidence > existingFAQ.confidence) {
      existingFAQ.answer = bestAnswer.answer;
      existingFAQ.confidence = bestAnswer.confidence;
    }

    // Update sentiment
    existingFAQ.avgSentiment =
      (existingFAQ.avgSentiment + similarQuestions[0].sentiment) /
      (similarQuestions.length + 1);

    existingFAQ.lastUpdated = new Date();
  }

  return existingFAQ;
}

/**
 * Calculate similarity between two questions
 */
function calculateSimilarity(q1: string, q2: string): number {
  const words1 = q1.toLowerCase().split(/\s+/);
  const words2 = q2.toLowerCase().split(/\s+/);

  const intersection = words1.filter((w) => words2.includes(w)).length;
  const union = new Set([...words1, ...words2]).size;

  return intersection / union;
}

/**
 * Track FAQ usage and satisfaction
 */
export async function trackFAQUsage(
  faqId: string,
  used: boolean,
  satisfactionRating?: number
): Promise<void> {
  if (used) {
    // Increment usage count
    // In production, update database
  }

  if (satisfactionRating !== undefined) {
    // Update satisfaction score
    // In production, update database
  }
}

/**
 * Get trending questions that should become FAQs
 */
export async function getTrendingQuestions(
  dealershipId: number,
  minFrequency: number = 3,
  minConfidence: number = 60
): Promise<ExtractedQuestion[]> {
  // In production, query database for conversations
  return [];
}

/**
 * Auto-improve FAQ answers based on feedback
 */
export async function improveAnswerBasedOnFeedback(
  faq: AutoGeneratedFAQ,
  userFeedback: string,
  rating: number
): Promise<AutoGeneratedFAQ> {
  // If rating is low, mark for improvement
  if (rating < 3) {
    // Trigger LLM to generate better answer
    // In production, call LLM service
  }

  // Track feedback for learning
  faq.satisfactionScore = (faq.satisfactionScore + rating) / 2;

  return faq;
}

/**
 * Generate FAQ summary for admin dashboard
 */
export async function getFAQSummary(dealershipId: number): Promise<{
  totalFAQs: number;
  autoGeneratedFAQs: number;
  avgConfidence: number;
  avgSatisfaction: number;
  topCategories: { category: string; count: number }[];
  recentlyAdded: AutoGeneratedFAQ[];
  needsImprovement: AutoGeneratedFAQ[];
}> {
  return {
    totalFAQs: 0,
    autoGeneratedFAQs: 0,
    avgConfidence: 0,
    avgSatisfaction: 0,
    topCategories: [],
    recentlyAdded: [],
    needsImprovement: [],
  };
}

/**
 * Batch process conversations to generate FAQs
 */
export async function batchProcessConversations(
  dealershipId: number,
  conversations: ConversationMessage[][]
): Promise<AutoGeneratedFAQ[]> {
  // Extract questions
  const extracted = await extractQuestionsFromConversations(conversations);

  // Generate FAQs
  const faqs = await generateFAQsFromExtracted(extracted, dealershipId);

  // Save to database (in production)
  // await saveFAQsToDatabase(dealershipId, faqs);

  return faqs;
}
